_format_version: "2.1"
_transform: true

consumers:
- username: authuser
- username: anonymous

jwt_secrets:
- consumer: authuser
  secret: finclip
  key: ek5XS0x1SW9ZUkpubVR2aFY3U1dQOUVMcDJoL2hsYUloem1XMFFscHBBST0K

services:
- name: mop-app-manage-svr
  url: http://mop-app-manage-svr:8080/api/v1/mop/finstore
  routes:
  - name: mop-app-manage-svr
    paths:
    - /api/v1/mop/finstore
    - /api/v1/mop/pc
    - /api/v1/mop/widget

- name: mop-app-manage-svr-v2
  url: http://mop-app-manage-svr:8080/api/v2/mop/finstore
  routes:
  - name: mop-app-manage-svr-v2
    paths:
    - /api/v2/mop/finstore


- name: mop-app-manage-svr-no-auth
  url: http://mop-app-manage-svr:8080
  routes:
  - name: mop-app-manage-svr-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/finstore/runtime

- name: mop-applet-build-manager
  url: http://mop-applet-build-manager:8080
  connect_timeout: 60000000
  write_timeout: 60000000
  read_timeout: 60000000
  routes:
  - name: mop-applet-build-manager
    strip_path: false
    paths:
    - /api/v1/mop/mop-applet-build-manager
    - /api/v2/mop/mop-applet-build-manager
    - /api/v2/mop/mop-applet-build-manager-v2
    - /api/v1/mop/mop-applet-build-manager-ide

- name: mop-applet-build
  url: http://mop-applet-build:8080/api/v1/mop/build
  routes:
  - name: mop-applet-build
    paths:
    - /api/v1/mop/build
  connect_timeout: 600000
  write_timeout: 600000
  read_timeout: 600000

- name: mop-data-report-no-auth
  url: http://mop-data-report:8080
  routes:
  - name: mop-data-report-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/data-report/reportmsg/report
    methods:
    - POST

- name: mop-front-mechanism
  url: http://mop-front-mechanism:80/mop/mechanism
  routes:
  - name: mop-front-mechanism
    paths:
    - /mop/mechanism

- name: mop-front-operate
  url: http://mop-front-operate:80/mop/operate
  routes:
  - name: mop-front-operate
    paths:
    - /mop/operate

- name: mop-account-system
  url: http://mop-account-system:8080/api/v1/mop/applets-ecol-account
  routes:
  - name: mop-account-system
    paths:
    - /api/v1/mop/applets-ecol-account
    - /api/v2/mop/applets-ecol-account

- name: mop-account-system-v2
  url: http://mop-account-system.finclip.svc.cluster.local:8080/api/v2/mop/applets-ecol-account
  routes:
  - name: mop-account-system-v2
    paths:
    - /api/v2/mop/applets-ecol-account

- name: mop-account-system-no-auth
  url: http://mop-account-system:8080
  routes:
  - name: mop-account-system-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/applets-ecol-account/organ/auth/get-evn
    - /api/v1/mop/applets-ecol-account/organ/phone/verifyCode
    - /api/v1/mop/applets-ecol-account/organ/phone/verify-code
    - /api/v1/mop/applets-ecol-account/organ/register
    - /api/v1/mop/applets-ecol-account/organ/login
    - /api/v1/mop/applets-ecol-account/organ/phone/verifyCode/check
    - /api/v1/mop/applets-ecol-account/organ/phone/verify-code/check
    - /api/v1/mop/applets-ecol-account/operation/login
    - /api/v1/mop/applets-ecol-account/organ/account/password/forget
    - /api/v1/mop/applets-ecol-account/operation/worker/phone/verifyCode
    - /api/v1/mop/applets-ecol-account/operation/worker/phone/verify-code
    - /api/v1/mop/applets-ecol-account/operation/worker/forgot/password
    - /api/v1/mop/applets-ecol-account/operation/organ/addAppidNum
    - /api/v1/mop/applets-ecol-account/operation/organ/add-appid-num
    - /api/v1/mop/applets-ecol-account/operation/ftHelper/testUrl
    - /api/v1/mop/applets-ecol-account/operation/ft-helper/test-url
    - /api/v1/mop/applets-ecol-account/organ/email/active
    - /api/v1/mop/applets-ecol-account/common/check/passed-organ-limit
    - /api/v1/mop/applets-ecol-account/common/captcha
    - /api/v1/mop/applets-ecol-account/common/check/captcha
    - /api/v1/mop/applets-ecol-account/organ/check/has-registered
    - /api/v1/mop/applets-ecol-account/operation/worker/phone/check-code
    - /api/v1/mop/applets-ecol-account/common/check/captcha
    - /api/v2/mop/applets-ecol-account/organ/login
  - name: mop-account-system-GET-no-auth
    strip_path: false
    methods: ["GET"]
    paths:
    - /api/v1/mop/applets-ecol-account/common/scancode/login/generateUuid
  - name: mop-account-system-POST-no-auth
    strip_path: false
    methods: ["POST"]
    paths:
    - /api/v1/mop/applets-ecol-account/common/scancode/login/refreshLogin

- name: mop-notify
  url: http://mop-notify:8080/api/v1/mop/applets-ecol-notify
  routes:
  - name: mop-notify
    paths:
    - /api/v1/mop/applets-ecol-notify

- name: finclip-app-ext-svr
  url: http://finclip-app-ext-svr:8080/api/v1/mop/finclip-app-ext-svr
  routes:
  - name: finclip-app-ext-svr
    paths:
    - /api/v1/mop/finclip-app-ext-svr

- name: netdisk
  url: http://netdisk:9999/api/v1/netdisk
  routes:
  - name: netdisk
    paths:
    - /cust/api/v1/netdisk
    - /emp/api/v1/netdisk
    - /api/v1/netdisk

- name: netdisk-authless
  url: http://netdisk:9999
  routes:
  - name: netdisk-authless
    strip_path: false
    paths:
    - /api/v1/netdisk/download
    - /authless/api/v1/netdisk/download
    - /api/v1/netdisk/thumbnail
    - /api/v1/netdisk/upload/self

- name: mop-netdisk-no-auth
  url: http://netdisk:9999/api/v1/netdisk
  routes:
  - name: mop-netdisk-no-auth
    paths:
    - /api/v1/mop/netdisk

- name: mop-domain-manager
  url: http://mop-domain-manager:8080/api/v1/mop/applets-ecol-domain
  routes:
  - name: mop-domain-manager
    paths:
    - /api/v1/mop/applets-ecol-domain

- name: mop-data-report
  url: http://mop-data-report:8080
  routes:
  - name: mop-data-report
    strip_path: false
    paths:
    - /api/v1/mop/data-report


- name: mop-article-pub-center
  url: http://mop-article-pub-center:8080/api/v1/mop/mop-article-pub-center/article
  routes:
  - name: mop-article-pub-center
    paths:
    - /api/v1/mop/mop-article-pub-center/article

- name: mop-article-pub-center-no-auth
  url: http://mop-article-pub-center:8080
  routes:
  - name: mop-article-pub-center-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-article-pub-center/article/list
    - /api/v1/mop/mop-article-pub-center/article/detail
    - /api/v1/mop/mop-article-pub-center/article/rotation
    - /api/v1/mop/mop-article-pub-center/article/rotation/list
    - /api/v1/mop/mop-article-pub-center/article/wechat/appCode
    - /api/v1/mop/mop-article-pub-center/article/wechat/app-code

  - name: mop-article-pub-center-GET-no-auth
    strip_path: false
    methods: ["GET"]
    paths:
    - /api/v1/mop/mop-article-pub-center/article/advertise/getOnlineAdvertise
    - /api/v1/mop/mop-article-pub-center/article/material/getOnline

- name: mop-scattered-page
  url: http://mop-scattered-page:80/mop/mop-scattered-page
  routes:
  - name: mop-scattered-page
    paths:
    - /mop/scattered-page
    - /mop/mop-scattered-page

- name: mop-basic-pack-svr
  url: http://mop-basic-pack-svr:8080
  routes:
  - name: mop-basic-pack-svr
    strip_path: false
    paths:
    - /api/v1/mop/mop-basic-pack-svr

  - name: mop-basic-pack-svr-GET-no-auth
    strip_path: false
    methods: ["GET"]
    paths:
    - /api/v1/mop/mop-basic-pack-svr

- name: mop-feedback-svr
  url: http://mop-feedback-svr:8080/api/v1/mop/mop-feedback-svr
  routes:
  - name: mop-feedback-svr
    paths:
    - /api/v1/mop/mop-feedback-svr

- name: mop-feedback-svr-no-auth
  url: http://mop-feedback-svr:8080
  routes:
  - name: mop-feedback-svr-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-feedback-svr/data


- name: mop-netdisk-proxy
  url: http://mop-netdisk-proxy:8080
  routes:
  - name: mop-netdisk-proxy
    strip_path: false
    paths:
    - /api/v1/mop/netDiskProxy/normal
    - /api/v1/mop/netdisk-proxy/normal

- name: mop-netdisk-proxy-no-auth
  url: http://mop-netdisk-proxy:8080
  routes:
  - name: mop-netdisk-proxy-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/netDiskProxy/needCheckAuth
    - /api/v1/mop/netdisk-proxy/need-check-auth


- name: mop-fast-trial-manager
  url: http://mop-fast-trial-manager:8080/api/v1/mop/mop-fast-trial-manager
  routes:
  - name: mop-fast-trial-manager
    paths:
    - /api/v1/mop/mop-fast-trial-manager

  - name: mop-fast-trial-manager-post-no-jwt
    methods: ["POST"]
    paths:
    - /api/v1/mop/mop-fast-trial-manager/hackathon/save/signup-msg

  - name: mop-fast-trial-manager-get-no-jwt
    methods: ["GET"]
    paths:
    - /api/v1/mop/mop-fast-trial-manager/hackathon/get/team-score

- name: mop-open-api-no-auth
  url: http://mop-open-api:8080
  routes:
  - name: mop-open-api-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-open-api
    - /api/v1/mop/openapi
    - /api/v1/mop/runtime
    - /api/v1/mop/open-api

- name: mop-control-manager
  url: http://mop-control-manager:8080/api/v1/mop/mop-control-manager
  routes:
  - name: mop-control-manager
    paths:
    - /api/v1/mop/mop-control-manager

- name: mop-control-manager-no-auth
  url: http://mop-control-manager:8080
  routes:
  - name: mop-control-manager-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-control-manager/mopHelper/ios/version/auditing
    - /api/v1/mop/mop-control-manager/mop-helper/ios/version/auditing
    - /api/v1/mop/mop-control-manager/mopSDK/config/info
    - /api/v1/mop/mop-control-manager/mop-sdk/config/info

- name: mop-control-manager-GET-no-auth
  url: http://mop-control-manager:8080
  routes:
  - name: mop-control-manager-GET-no-auth
    strip_path: false
    methods: ["GET"]
    paths:
    - /api/v1/mop/mop-control-manager/mopHelper/config/info

- name: mop-fast-trial-manager-no-auth
  url: http://mop-fast-trial-manager:8080
  routes:
  - name: mop-fast-trial-manager-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-fast-trial-manager/verifyCode
    - /api/v1/mop/mop-fast-trial-manager/verify-code
    - /api/v1/mop/mop-fast-trial-manager/info/apply
    - /mop-fast-trial-manager/info/show
    - /api/v1/mop/mop-fast-trial-manager/info/show
    - /api/v1/mop/mop-fast-trial-manager/send/account
    - /api/v1/mop/mop-fast-trial-manager/web/visits/statistics

- name: mop-fast-trial-manager
  url: http://mop-fast-trial-manager:8080/api/v1/mop/mop-fast-trial-manager
  routes:
  - name: mop-fast-trial-manager
    paths:
    - /api/v1/mop/mop-fast-trial-manager

- name: mop-device-security
  url: http://mop-device-security:8080/api/v1/mop/applets-ecol-device-security
  routes:
  - name: mop-device-security
    paths:
    - /api/v1/mop/applets-ecol-device-security

- name: mop-device-security-no-auth
  url: http://mop-device-security:8080
  routes:
  - name: mop-device-security-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/applets-ecol-device-security/refresh/token

- name: mop-rule-engine-svr
  url: http://mop-rule-engine-svr:8080
  routes:
  - name: mop-rule-engine-svr
    strip_path: false
    paths:
    - /api/v1/mop/ruleEngine
    - /api/v1/mop/rule-engine

- name: mop-help-center-svr
  url: http://mop-help-center-svr:8080/api/v1/mop/help-center
  routes:
  - name: mop-help-center-svr
    paths:
    - /api/v1/mop/help-center

- name: mop-app-gray-statistics-center
  url: http://mop-app-gray-statistics-center:8080/api/v1/mop/mop-app-gray-statistics-center
  routes:
  - name: mop-app-gray-statistics-center
    paths:
    - /api/v1/mop/mop-app-gray-statistics-center

- name: mop-sdk-manager
  url: http://mop-sdk-manager:8080/api/v1/mop/mop-sdk-manager
  routes:
  - name: mop-sdk-manager
    paths:
    - /api/v1/mop/mop-sdk-manager

- name: mop-audit-manage-svr
  url: http://mop-audit-manage-svr:8080/api/v1/mop/mop-audit-manage-svr
  routes:
  - name: mop-audit-manage-svr
    paths:
    - /api/v1/mop/mop-audit-manage-svr

- name: mop-front-document
  url: http://mop-front-document:80/mop/document
  routes:
  - name: mop-front-document
    paths:
    - /mop/document

- name: applets-docs
  url: http://applet-doc:80
  routes:
  - name: applets-docs
    paths:
    - /docs

- name: mop-purchasing-rights-manager
  url: http://mop-purchasing-rights-manager:8080/api/v1/mop/mop-purchasing-rights-manager
  routes:
  - name: mop-purchasing-rights-manager
    paths:
    - /api/v1/mop/mop-purchasing-rights-manager

- name: mop-purchasing-rights-manager-no-auth
  url: http://mop-purchasing-rights-manager:8080
  routes:
  - name: mop-purchasing-rights-manager-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-purchasing-rights-manager/1yuan/100yuan-coupon/buy
    - /api/v1/mop/mop-purchasing-rights-manager/rights/order

- name: mop-data-static
  url: http://mop-data-static:8080
  routes:
  - name: mop-data-static
    strip_path: false
    paths:
    - /api/v1/mop/data-static

- name: mop-ide-access-svr-no-auth
  url: http://mop-ide-access-svr:8080
  routes:
  - name: mop-ide-access-svr-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-ide-access-svr

- name: headers
  url: http://headers:8080
  routes:
  - name: headers
    paths:
    - /headers

- name: mop-worksheet-system
  url: http://mop-worksheet-system:8080/api/v1/mop/worksheet-system
  routes:
  - name: mop-worksheet-system
    paths:
    - /api/v1/mop/worksheet-system

- name: mop-worksheet-system-no-auth
  url: http://mop-worksheet-system:8080
  routes:
  - name: mop-worksheet-system-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/worksheet-system/organ/anonymous/add

- name: mop-app-search
  url: http://mop-app-search:8080
  routes:
  - name: mop-app-search
    strip_path: false
    paths:
    - /api/v1/mop/mop-app-search/app/recent/visit

- name: mop-app-search-no-auth
  url: http://mop-app-search:8080
  routes:
  - name: mop-app-search-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-app-search

- name: finclip-data-counter
  url: http://finclip-data-counter:8080
  routes:
  - name: finclip-data-counter
    strip_path: false
    paths:
    - /api/v1/mop/finclip-data-counter

- name: mop-applet-build-manager-no-auth
  url: http://mop-applet-build-manager:8080
  routes:
  - name: mop-applet-build-manager-no-auth
    strip_path: false
    paths:
    - /api/v2/mop/mop-applet-build-manager/plugin/ide/version/info

- name: trade-server-no-auth
  url: http://trade-server:8080
  routes:
  - name: trade-server-no-auth
    strip_path: false
    paths:
    - /api/v1/finogeeks/trade-server/notify/wx

- name: finclip-customer-open-api-no-auth
  url: http://finclip-customer-open-api:8080
  routes:
  - name: finclip-customer-open-api-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/finclip-customer-open-api

- name: mop-auth-checker-no-auth
  url: http://mop-auth-checker:8080
  routes:
  - name: mop-auth-checker-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-auth-checker/auth/tree

- name: mop-auth-checker
  url: http://mop-auth-checker:8080
  routes:
  - name: mop-auth-checker
    strip_path: false
    paths:
    - /api/v1/mop/mop-auth-checker

- name: mop-account-strategy-no-auth
  url: http://mop-account-strategy:8080
  routes:
  - name: mop-account-strategy-no-auth
    strip_path: false
    paths:
    - /api/v1/mop/mop-account-strategy

- name: mop-miniprogram-preview-no-auth
  url: http://mop-miniprogram-preview:8080
  routes:
  - name: mop-miniprogram-preview-no-auth
    strip_path: true
    paths:
    - /mop/preview

- name: mop-front-login-no-auth
  url: http://mop-front-login:8080
  routes:
  - name: mop-front-login-no-auth
    strip_path: false
    paths:
    - /login

- name: mop-front-cms-no-auth
  url: http://mop-front-cms:8080
  routes:
  - name: mop-front-cms-no-auth
    strip_path: false
    paths:
    - /mop/cms

plugins:
- name: prometheus

- name: jwt
  config:
    secret_is_base64: true
    claims_to_verify:
    - exp
    uri_param_names:
    - jwt
    maximum_expiration: 86400

- name: jwt-claims-to-headers
  config:
    header_prefix: x-mop-

#authless
- name: jwt
  config:
    anonymous: anonymous
  route: applets-docs
- name: jwt
  config:
    anonymous: anonymous
  route: mop-ide-access-svr-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-purchasing-rights-manager-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-account-system-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-account-system-GET-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-account-system-POST-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-article-pub-center-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-app-manage-svr-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-control-manager-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-control-manager-GET-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-data-report-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-device-security-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-fast-trial-manager-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-feedback-svr-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-front-mechanism
- name: jwt
  config:
    anonymous: anonymous
  route: mop-front-operate
- name: jwt
  config:
    anonymous: anonymous
  route: mop-help-center-svr
- name: jwt
  config:
    anonymous: anonymous
  route: mop-netdisk-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-open-api-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-scattered-page
- name: jwt
  config:
    anonymous: anonymous
  route: netdisk-authless
- name: jwt
  config:
    anonymous: anonymous
  route: mop-front-document
- name: jwt
  config:
    anonymous: anonymous
  route: mop-netdisk-proxy-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-app-search-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-worksheet-system-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-applet-build-manager-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: trade-server-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: finclip-customer-open-api-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-auth-checker-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-basic-pack-svr-GET-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-article-pub-center-GET-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-account-strategy-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-miniprogram-preview-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-front-login-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-front-cms-no-auth
- name: jwt
  config:
    anonymous: anonymous
  route: mop-fast-trial-manager-post-no-jwt
- name: jwt
  config:
    anonymous: anonymous
  route: mop-fast-trial-manager-get-no-jwt

